# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    env:
      PORT: "3002"
      DB_NAME_CG: "pa7_cg"
      DB_NAME_CG2: "pa7"
      DB_NAME_GF: "pa7_gf_test_2"
      DB_NAME_ALI: "pa7"
      DB_NAME_AUT: "pa7"
      DB_NAME_CH: "pa7"
      DB_NAME_DET: "pa7"
      DB_NAME_ELY: "pa7"
      DB_NAME_LUX: "pa7_gf_test_2"
      DB_USERNAME2: "franco"
      DB_USERNAME: "admin"
      DB_PASSWORD2: "password"
      DB_PASSWORD: "Juan_172o"
      DB_HOST2: "giama-db-t3.cojfgn4yxtap.us-west-2.rds.amazonaws.com"
      DB_HOST: "giama-test.cojfgn4yxtap.us-west-2.rds.amazonaws.com"
      DB_DIALECT: "mysql"
      SECRET: "JWT_SECRET"
      RESET_SECRET: "MY_SECRET"
      HOST: "http://localhost:3000"
      MAIL_HOST: "mail.giama.com.ar"
      MAIL_USER: "info@giama.com.ar"
      MAIL_PASS: "Q)9~X-?(5~,o"

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm run build --if-present
      - run: |
          touch .env
          echo DB_DIALECT="mysql" >> .env
          echo PORT="3002" >> .env
          echo DB_NAME_CG="pa7_cg" >> .env
          echo DB_NAME_CG2="pa7" >> .env
          echo DB_NAME_GF="pa7_gf_test_2" >> .env
          echo DB_NAME_ALI="pa7" >> .env
          echo DB_NAME_AUT="pa7" >> .env
          echo DB_NAME_CH="pa7" >> .env
          echo DB_NAME_DET="pa7" >> .env
          echo DB_NAME_ELY="pa7" >> .env
          echo DB_NAME_LUX="pa7_gf_test_2" >> .env
          echo DB_USERNAME2="franco" >> .env
          echo DB_USERNAME="admin" >> .env
          echo DB_PASSWORD2="password" >> .env
          echo DB_PASSWORD="Juan_172o" >> .env
          echo DB_HOST2="giama-db-t3.cojfgn4yxtap.us-west-2.rds.amazonaws.com" >> .env
          echo DB_HOST="giama-test.cojfgn4yxtap.us-west-2.rds.amazonaws.com" >> .env
          echo DB_DIALECT="mysql" >> .env
          echo SECRET="JWT_SECRET" >> .env
          echo RESET_SECRET="MY_SECRET" >> .env
          echo HOST="http://localhost:3000" >> .env
          echo MAIL_HOST="mail.giama.com.ar" >> .env
          echo MAIL_USER="info@giama.com.ar" >> .env
          echo MAIL_PASS="Q)9~X-?(5~,o" >> .env
      - run: sudo pm2 restart 0
